# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish node-sql-parser package to GitHub Packages
on:
  push:
    branches:
      - spark
  # release:
  #   types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v5

      # Set build type dev/prod based on branch
      - name: Set build type
        run: echo "BUILD_TYPE=$(if [ '${{ github.ref }}' != 'refs/heads/master' ]; then echo 'dev'; else echo 'prod'; fi)" >> $GITHUB_ENV

      # Setup .npmrc file to publish to GitHub Packages
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@KronML' # Defaults to the user or organization that owns the workflow file

      # Configure Git for version bumping
      - name: Configure Git
        run: |
          git config --global user.email "kronml-github-actions[bot]@users.noreply.github.com"
          git config --global user.name "kronml-github-actions[bot]"

      # Bump version
      - name: Bump version
        run: |
          if [ "$BUILD_TYPE" = "dev" ]; then
            npm version prerelease --preid=dev -m "Bump version to %s [skip ci]"
          else
            npm version patch -m "Bump version to %s [skip ci]"
          fi

  # Publish to npm only for prod builds, publish to GitHub Packages for both dev and prod builds
  publish-npm:
    if: needs.build.outputs.BUILD_TYPE == 'prod'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: https://registry.npmjs.org/
          org: '@kronml'

      - run: npm install

      - run: npm run build

      - run: cd output/prod && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_NPM_TOKEN }}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@kronml'

      # Publish package to GitHub Packages
      - name: Publish package to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
