# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish node-sql-parser package to GitHub Packages
on:
  push:
    branches:
      - spark
  # release:
  #   types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v5

      # Setup .npmrc file to publish to GitHub Packages
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@KronML' # Defaults to the user or organization that owns the workflow file

      # Configure Git for version bumping
      - name: Configure Git
        run: |
          git config --global user.email "kronml-github-actions[bot]@users.noreply.github.com"
          git config --global user.name "kronml-github-actions[bot]"

      # Bump version
      - name: Bump version
        run: npm version patch -m "Bump version to %s [skip ci]"

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Publish package to GitHub Packages
      - name: Publish package to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
